name: Check Enforcer

on:
  check_suite:
    types: [completed]
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  check-enforcer:
    name: Handle Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Sparse Checkout Tools
        env:
          GH_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "bbp"
          ls -R
          echo "bbp2"

          git clone --no-checkout --filter=tree:0 https://github.com/benbp/azure-sdk-tools .
          git sparse-checkout init
          git sparse-checkout set '/.github/*' '/tools/check-enforcer-action'
          git checkout main

          ls -R

          cd ./tools/check-enforcer-action
          echo "$GH_PAYLOAD" > ./gh_payload.json
          go run . ./gh_payload.json
