on:
  workflow_dispatch:
  push:
    branches:
      - main
      - oidctesting

permissions:
  id-token: write
  contents: read

jobs:
  oidc:
    environment: keyvault-demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd

    - name: 'Call issue label service'
      working-directory: tools/oidc-demo
      run: |
        export TOKEN=$(az account get-access-token \
          --resource 35396473-8019-4752-828d-56d17159c02e \
          --query "accessToken" \
          --output tsv)

        # DEBUG
        az keyvault secret set \
          --vault-name bebrodergithubactions --name oidcdebug  --value "$TOKEN"

        echo "::add-mask::$TOKEN"

        dotnet run

#  az rest \
#    --method POST \
#    --resource "a6dd2dfe-7352-41a7-9020-05301c3bca1a" \
#    --uri "https://bebroderoidcapp.azurewebsites.net/api/AzureSdkIssueLabelerService" \
#    --body '{"IssueNumber":"33697","Title":"[FEATURE REQ]","body":"Azure.Messaging.EventHubs","IssueUserLogin":"benbp","RepositoryName":"azure-sdk-for-net","RepositoryOwnerName":"Azure"}'
