name: Check Run Gate

on:
  check_run:
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull Request Check URI
        run: echo ${{ github.event.check_run.html_url }}

      - name: Pull Request Number
        run: echo ${{ github.event.check_run.check_suite.pull_requests[0].number }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
